project:
  type: website

execute:
  freeze: auto

website:
  title: "Celestia's World"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Webster_Fam.qmd
      - Map_C_Network.qmd
      - Map_C_Boarding.qmd
      - Map_C_Zerviah.qmd
  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

