---
title: Celestia's World
execute:
  echo: false
---

*"My throat troubles me considerable this winter. I begin to be afraid that it is going to be something serious. It hurts me to talk after talking so much in school, I have been very quiet."*

**Celestia Webster's Diary - January 9, 1867**

  Celestia Webster, a school teacher from the small, rural town of Conesus, New York, kept a diary from 1866 to 1867. In its pages, she described the lives of her family members, town events, and community relationships. She chronicled her deepest thoughts on grief, the afterlife, and Christianity in the wake of both her father's passing and her sister, Wealthy's death from tuberculosis. Most significantly, Celestia kept track of her own struggle with chronic illness beginning in 1867. Her life offers an intimate look into the everyday life of a nineteenth century women learning to manage her physical and emotional pain. Along the way, she lost her job and her social energy that defined her personality. Through all of it, she maintained a sense of optimism that comes through her cursive handwriting. 

