---
title: Celestia's Network
execute:
  echo: false
---

*"The Lord has been and is very kind to me in giving me so many friends may I ever be grateful for all his benefits."*

**Celestia Webster's Diary - May 17, 1867**

## Celestia's Network in Livingston County, New York

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(sf)
library(leaflet)
library(paletteer)
library(terra)
library(tidyterra)
library(ggplot2)

networklocations <- read_csv("C_Network.csv")

locations_sf <- st_as_sf(networklocations,
                         coords = c("lng", "lat"),
                         crs = 4326)
livingston <- rast("1850.tif")

#ggplot map with historical map
ggplot() +
  tidyterra::geom_spatraster_rgb(data = livingston) +
  geom_sf(data = locations_sf, fill = NA, color = "blue") +
  theme_minimal ()

# Leaflet map without historical map

pal <- colorFactor(
  palette = as.character(paletteer_d("colorBlindness::paletteMartin")),
  domain = locations_sf$`diary location`
)


leaflet() |> 
  addTiles() |>
  addCircleMarkers(data = locations_sf,
                   fillOpacity = 0.5,
                   color = ~pal,
                   radius = 5,
                   label = ~ locations_sf$`diary location`) |>
  addLegend("topleft", pal = pal, values = locations_sf$`diary location`)
          
  
```

```{r}
"library(sf)
library(tidygeocoder)
library(USAboundaries)
library(tidyverse)

cnetwork <- read.csv(C_Network.csv)

locations <- geo(c(Conesus, Livonia, Springwater, Hemlock))
locations

locations_sf <- st_as_sf(cnetwork, coords = c(lng, lat), crs = 4326)
locations_sf

newyork <- us_counties(states = New York)

# Find EPSG code for New York
state_plane(state = NY)

# Project
locs_proj <- st_transform(locations_sf, EPSG:32146)
newyork_proj <- st_transform(newyork, EPSG:32116)

ggplot() + 
  geom_sf(data = newyork_proj) + 
  geom_sf(data = locs_proj) + 
  labs(title = Celestia's Network in Livingston County)
  theme_minimal()
location <- networklocations
                   filter (column_ == diary location) - this is for point map
ggplot() + 
  geom_sf(data = newyork_proj) + 
  geom_sf(data = locs_proj) +
  coord_sf(xlim = c(-76.0,-78.0),ylim = c(43.0,42.0))"
```
