---
title: The Webster Family
---

*"How wise and good in God to grant us friends, he has bound us together by the ties of blood that can never be sundered We should be ever trying to do each other good to help each other on in our journey to the kingdom"*

**Celestia Webster's Diary - March 31, 1866**

### Sickness in the Family

*"My heart is sad at the remembrance, that for the third time our family circle was broken four months ago today, then the head of our family our noble Christian father was torn from our embrace by the rude hand of Death My life seems to be a blank since then. I am so disconsolate and do not know what to set myself about."*

**Celestia Webster's Diary - April 1, 1866**

*"Since my last birthday sad, bitter change have taken place A loved father has been taken from us, We left a fatherless group of children with our widowed mother Oh how deeply we feel his loss. Since then sickness has been in our midst of we fear? that our family will perhaps be broken again...A short time before twelve some one rapped at the door, I went to the doors and was surprised to see Nelson there, he brought the news that both Lib and Wet were sick, he said Wet was very bad off; her lungs are so bad, he said that she had a very bad day a couple of days ago."*

**Celestia Webster's Diary - July 30-31, 1866**

*"Early this forenoon it rained some and has looked as though it was preparing for a heavy rain. Carrie and I sat up with Wet last night. Sue was up the most of the time too I sat on the edge of the bed fanning her and holding her hand occasionally rubbing her stomach when I was not waiting on her as she was vomiting from ten o’clock till four. She says to me I want you to stay with me as much as you can. She thinks we will not have her with us long. In the midst of her severe pain she exclaimed several times “bless the Lord” that it was no worse."*

**Celestia Webster's Diary -October 10, 1866**